### ISSUE TITLE
TextureRegions rendered upside down

### ISSUE THREAD

**Issue by danirod** [mini2Dx/mini2Dx#35]
I noticed that rendering TextureRegions via `Graphics.drawTextureRegion` renders them upside down, despite normal Textures rendering correctly. For instance, the following code:

```java
	@Override
    public void initialise() {
        sheet = new Texture("player_sheet.png");
        region = new TextureRegion(sheet, 0, 0, 24, 32);
    }
    
    @Override
    public void render(Graphics g) {
        g.setBackgroundColor(Color.GREEN);
        g.drawTextureRegion(region, 10, 10, 24, 32);
        g.drawTexture(sheet, 40, 40);
    }
```

Produces the following output:

<img width="165" alt="screen shot 2015-08-11 at 17 32 14" src="https://cloud.githubusercontent.com/assets/1568690/9202581/d236eefc-4052-11e5-81c2-8db92346bda8.png">

A workaround to this seems to be using negative height plus some vertical offset to make the TextureRegion render in the same location as the original image. Changing the call to this:

```java
        g.drawTextureRegion(region, 10, 10 + 32, 24, -32);
```

Produces the following output:

<img width="143" alt="screen shot 2015-08-11 at 17 39 00" src="https://cloud.githubusercontent.com/assets/1568690/9202626/0e2f4cd8-4053-11e5-8029-b2f371f0096c.png">

I'm looking into how to set up the core libraries in my computer to see if I can patch this behaviour and send back a pull request to this project. In the meantime I thought it was a good idea informing you about this bug.

**Comment by tomcashman** [comment]
It is a known issue due to LibGDX setting 0,0 as the bottom left corner whereas mini2Dx places it in the top left.

The easy solution is to pass your TextureRegion into a [mini2Dx Sprite instance](http://mini2dx.org/javadoc/1.1.0/org/mini2Dx/core/graphics/Sprite.html) which will flip it for you.

We really need a permanent solution that will auto-flip Texture and TextureRegion instances when they are loaded.
